// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwfEZgTV3ZPEDZjx8i0DOtANMw2i1eyk',
    appId: '1:321198405383:web:94872e53ff639ed3ce37a2',
    messagingSenderId: '321198405383',
    projectId: 'todo-list-52597',
    authDomain: 'todo-list-52597.firebaseapp.com',
    storageBucket: 'todo-list-52597.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74THQrnN2AbMKTUIBLdZRB6w0RyrVi8E',
    appId: '1:321198405383:android:27281a7575202befce37a2',
    messagingSenderId: '321198405383',
    projectId: 'todo-list-52597',
    storageBucket: 'todo-list-52597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlIPmW568dOnhD60izTxf-VErz_iCesL4',
    appId: '1:321198405383:ios:8f84bca78e1529d0ce37a2',
    messagingSenderId: '321198405383',
    projectId: 'todo-list-52597',
    storageBucket: 'todo-list-52597.appspot.com',
    iosBundleId: 'com.example.toDoListApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlIPmW568dOnhD60izTxf-VErz_iCesL4',
    appId: '1:321198405383:ios:8f84bca78e1529d0ce37a2',
    messagingSenderId: '321198405383',
    projectId: 'todo-list-52597',
    storageBucket: 'todo-list-52597.appspot.com',
    iosBundleId: 'com.example.toDoListApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFwfEZgTV3ZPEDZjx8i0DOtANMw2i1eyk',
    appId: '1:321198405383:web:18106230e72bd2e1ce37a2',
    messagingSenderId: '321198405383',
    projectId: 'todo-list-52597',
    authDomain: 'todo-list-52597.firebaseapp.com',
    storageBucket: 'todo-list-52597.appspot.com',
  );
}
